### PR TITLE
Hotfix update disarm

### PR DESCRIPTION
**Pull request by jsebold666**
## Summary by CodeRabbit

- **New Features**
	- Introduced new macro types: `DisarmAbility` and `StunAbility`, allowing players to execute these actions through macros.
	- Updated ability usage logic to send specific requests based on client version, enhancing gameplay interactions.

- **Bug Fixes**
	- Fixed issues related to the Disarm and Stun abilities.

- **Documentation**
	- Added a new version entry for version `3.23.2` in the version history, detailing the latest updates. 

- **Chores**
	- Incremented assembly version to `3.23.2`.

### CODE REVIEW

**Comment by LasherasGH** [comment]
Hi, i found a issue related with this new feature/update.

When you open the options menu with a old profile with some old MacroType enum values (AKA: Action Code) it crashes the games when try to parse to some wrong MacroObject to visual components, i tried with "InvokeVirtue/Honor", this happen since enum VALUES has changed.

Macro XML sample:
```

<macro name="alt+3" key="51" mousebutton="0" wheelscroll="False" wheelup="False" alt="True" ctrl="False" shift="False" hidelabel="False" hue="0" graphic="" scale="100">
		<actions>
			<action code="47" subcode="59" submenutype="1" />
		</actions>
	</macro>
```

Old Action code = 47, new = 49.

**Comment by jsebold666** [comment]
@LasherasGH 
This pullrequest isn't even in the version you're running, how did you get this bug?
There is a channel for reporting.
https://discord.com/channels/1087124353155608617/1087124353692475454
Reporting on an already closed pullrequest will not work.

**Comment by LasherasGH** [comment]
Hi @jsebold666,

Sorry but, I just cloned it to do some improvements and compile it, and saw it, and inform it, i'm understand this still in development, and thanks for your time.

Well, i think it's really self explandatory, whats the point to change a saved value on every profile computer a enum values? of course, it will broke all profiles, and in the honor case, with old saves it crash the game when you open the options to try to change it. And it happens on every value after DisarmAbility.

I'm coommented here because i saw the commits/merges trying to half fix it.

Anyways, there is the crash log (i also have with debug mode)

```

Exception:
System.IndexOutOfRangeException: Índice fuera de los límites de la matriz.
   en ClassicUO.Game.UI.Gumps.ModernOptionsGump.ComboBoxWithLabel.Combobox..ctor(Int32 width, String[] items, Int32 selected, Int32 maxHeight, Action`2 onOptionSelected)
   en ClassicUO.Game.UI.Gumps.ModernOptionsGump.ComboBoxWithLabel..ctor(String label, Int32 labelWidth, Int32 comboWidth, String[] options, Int32 selectedIndex, Action`2 onOptionSelected)
   en ClassicUO.Game.UI.Gumps.ModernOptionsGump.MacroControl.MacroEntry.AddSubMacro(MacroObject obj)
   en ClassicUO.Game.UI.Gumps.ModernOptionsGump.MacroControl.MacroEntry..ctor(MacroControl control, MacroObject obj, String[] items)
   en ClassicUO.Game.UI.Gumps.ModernOptionsGump.MacroControl.SetupMacroUI()
   en ClassicUO.Game.UI.Gumps.ModernOptionsGump.MacroControl..ctor(String name)
   en ClassicUO.Game.UI.Gumps.ModernOptionsGump.BuildMacros()
   en ClassicUO.Game.UI.Gumps.ModernOptionsGump..ctor()
   en ClassicUO.Game.GameActions.OpenSettings(Int32 page)
   en ClassicUO.Game.UI.Gumps.ModernPaperdoll.MenuGump.<>c.<.ctor>b__0_2(Object s, MouseEventArgs e)
   en ClassicUO.Utility.Exstentions.Raise[T](EventHandler`1 handler, T e, Object sender) en D:\workspace\2024\TazUO\src\ClassicUO.Utility\Extensions.cs:línea 55
   en ClassicUO.Game.Managers.UIManager.OnMouseButtonUp(MouseButtonType button)
   en ClassicUO.GameController.HandleSdlEvent(IntPtr userData, IntPtr ptr)
   en SDL2.SDL.SDL_PollEvent(SDL_Event& _event)
   en Microsoft.Xna.Framework.SDL2_FNAPlatform.PollEvents(Game game, GraphicsAdapter& currentAdapter, Boolean[] textInputControlDown, Int32[] textInputControlRepeat, Boolean& textInputSuppress) en D:\workspace\2024\TazUO\external\FNA\src\FNAPlatform\SDL2_FNAPlatform.cs:línea 792
   en Microsoft.Xna.Framework.Game.RunLoop() en D:\workspace\2024\TazUO\external\FNA\src\Game.cs:línea 864
   en Microsoft.Xna.Framework.Game.Run() en D:\workspace\2024\TazUO\external\FNA\src\Game.cs:línea 416
   en ClassicUO.Client.Run()
   en ClassicUO.Bootstrap.Main(String[] args)
######################## [END LOG] ########################
```

i'm already on the discord channel (i'm Lasheras) but sorry i dont know your name, feel free to talk to me if you need to clarify anything further. 

TLDR: All saved macros after DisarmAbility enum was changed like honor Action Code = 47 new = 49. All profiles broken or crash.

Greetings.

**Comment by jsebold666** [comment]
@LasherasGH 
This has neither been applied nor validated, just developed, so your questions don't make sense.

And you're wrong, I'm not trying to fix it, it didn't even exist.

**Comment by LasherasGH** [comment]
i'm so sorry, i saw it on master misunderstanding it.

Thanks for your time.
Greetings.

**Comment by jsebold666** [comment]
@LasherasGH 
I'm working on migrating to net core 8 so things will change

**Pull request merged**
