### PR TITLE
Track GlobalMessages

### PR DESCRIPTION
**Pull request by elderwyn**
- This is attempting to intercept the CreateGump from Global Chat (864546439)
- Then inside JournalManager, I am reading and deconstructiong the lines of string into journal entries.
- Because the global chat gump call is sending all lines(messages) on each request, i have to hash the entries to avoid duplicates.
- Inside  AddJournalEntry you will see i am checking for the existing uint.

Again this is not elegant and more a hack.
The other option i was going to do was just raw feed the gump payload into an empty tab on ResizableJournal.

### CODE REVIEW

**Comment by bittiez** [comment]
Maybe I'm not understanding correctly but is this meant to parse the global chat from UOAlive?

**Comment by bittiez** [comment]
After having  tested this out, I see the idea and I'm impressed, however this only functions if UOAlives chat gump is already open which kind of defeats the purpose.. Unless UOAlive is willing to send some custom packets to the client where we don't need the gump open I'm probably going to close this one out

**Comment by elderwyn** [comment]
Did some more break pointing > the server does sent client notification of Global Chat entries 
PacketHandlers > UnicodeTalk > MessageManager.HandleMessage

You would need to check a few other parameters as well because this handle normal character chat as well.
entity == null  with serial == 4294967295
name  != "System"
hue == 1150
type == Regular
text_type  == SYSTEM

**Comment by bittiez** [comment]
Closing this unless UOAlive wants to add a custom packet sent on global chat messages

**Pull request closed without merging**
